apiVersion: v2
name: meshmonitor
description: A Helm chart for MeshMonitor - Web application for monitoring Meshtastic mesh networks
type: application
version: 3.0.0-beta4
appVersion: "3.0.0-beta4"
home: https://github.com/Yeraze/meshmonitor
sources:
  - https://github.com/Yeraze/meshmonitor
keywords:
  - meshtastic
  - monitoring
  - mesh-network
maintainers:
  - name: Yeraze
